config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :products
  resources :orders
  resources :buyers
  get 'home/index'

  get 'last_buyer', to: 'buyers#last_buyer'
  root 'home#index'
  # match '*path', to: 'home#index', via: :all
  get "*path", to: "home#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :orders
  has_many :products, through: :orders
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[ show edit update destroy ]

  # GET /buyers or /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1 or /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers or /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully created." }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1 or /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully updated." }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1 or /buyers/1.json
  def destroy
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url, notice: "Buyer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def last_buyer
    @last_buyer = Buyer.last.id 
    render json: { data: @last_buyer }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buyer_params
      params.require(:buyer).permit(:name, :address, :email, :cellphone, :payment)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_buyer.html.erb
<div id="<%= dom_id buyer %>">
  <p>
    <strong>Name:</strong>
    <%= buyer.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= buyer.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= buyer.email %>
  </p>

  <p>
    <strong>Cellphone:</strong>
    <%= buyer.cellphone %>
  </p>

  <p>
    <strong>Payment:</strong>
    <%= buyer.payment %>
  </p>

</div>

app/views/buyers/_form.html.erb
<%= form_with(model: buyer) do |form| %>
  <% if buyer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
        <% buyer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cellphone, style: "display: block" %>
    <%= form.text_field :cellphone %>
  </div>

  <div>
    <%= form.label :payment, style: "display: block" %>
    <%= form.text_field :payment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing buyer</h1>

<%= render "form", buyer: @buyer %>

<br>

<div>
  <%= link_to "Show this buyer", @buyer %> |
  <%= link_to "Back to buyers", buyers_path %>
</div>

app/views/buyers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buyers</h1>

<div id="buyers">
  <% @buyers.each do |buyer| %>
    <%= render buyer %>
    <p>
      <%= link_to "Show this buyer", buyer %>
    </p>
  <% end %>
</div>

<%= link_to "New buyer", new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New buyer</h1>

<%= render "form", buyer: @buyer %>

<br>

<div>
  <%= link_to "Back to buyers", buyers_path %>
</div>

app/views/buyers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @buyer %>

<div>
  <%= link_to "Edit this buyer", edit_buyer_path(@buyer) %> |
  <%= link_to "Back to buyers", buyers_path %>

  <%= button_to "Destroy this buyer", @buyer, method: :delete %>
</div>